receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  tail_sampling:
    decision_wait: 10s
    num_traces: 50000
    policies:
      - name: drop-mcp-traces
        type: string_attribute
        string_attribute:
          key: http.route
          values: ["/mcp"]
          invert_match: true

exporters:
  otlphttp/langfuse:
    endpoint: http://langfuse-web:3000/api/public/otel
    headers:
      Authorization: "Basic cGstMTIzNDU2Nzg5OnNrLTEyMzQ1Njc4OQ==" # pk-123456789:sk-123456789
  debug:
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tail_sampling, batch]
      exporters: [otlphttp/langfuse]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
